### ISSUE TITLE
RuntimeError: no acceptor

### ISSUE THREAD

**Issue by hansy** [guard/guard-livereload#135]
After upgrading to Ruby 2.2.2, I ran guard with `guard -d`, and got this output:

```
20:55:48 - DEBUG - Hook :start_begin executed for Guard::LiveReload
20:55:48 - ERROR - Guard::LiveReload failed to achieve its <start>, exception was:
> [#F40028E9D180] RuntimeError: no acceptor (port is in use or requires root privileges)
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_tcp_server'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_server'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-livereload-2.4.0/lib/guard/livereload/reactor.rb:50:in `block in _start_reactor'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-livereload-2.4.0/lib/guard/livereload/reactor.rb:49:in `_start_reactor'
> [#F40028E9D180] /Users/hansy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-livereload-2.4.0/lib/guard/livereload/reactor.rb:11:in `block in initialize'
20:55:48 - INFO - Guard::LiveReload has just been fired
``` 
Thoughts?

**Comment by hansy** [comment]
Had to assign a different port, but still don't know why this is happening.

**Comment by mokolabs** [comment]
I just ran into this problem too. You don't necessarily need to restart. Just make sure you kill all Ruby processes that are currently running on your machine -- either manually or by running a command like: `pgrep ruby | xargs sudo kill -9`) -- and then restart guard.
