### ISSUE TITLE
Not working with Ruby 2.4.0 and Rails 5.0.1

### ISSUE THREAD

**Issue by gregblass** [guard/guard-livereload#173]
bundle exec guard
12:07:50 - ERROR - Invalid Guardfile, original error is: 
`
> [#] 
> [#] cannot load such file -- guard/rspec/dsl,
> [#] backtrace: 
> [#] 	(dsl)> ./Guardfile:67:in `require'
> [#] 	(dsl)> ./Guardfile:67:in `block in evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/dsl.rb:178:in `guard'
> [#] 	(dsl)> ./Guardfile:66:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/dsl.rb:377:in `instance_eval'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/dsl.rb:377:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/guardfile/evaluator.rb:89:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard.rb:134:in `_evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard.rb:49:in `setup'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/commander.rb:32:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/cli.rb:122:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.14.0/bin/_guard-core:11:in `<main>'
`

**Comment by gregblass** [comment]
Any hope here? I've been doing a lot of front-end work with a Rails 5 project, and it is so painful to have to refresh the browser every time.

Does anyone know of any other ways to accomplish live reloading with Rails 5?

**Comment by gregblass** [comment]
This is not the issue. I had a reference to guard-rspec in my guardfile, but didn't have the gem included in my gemfile. Its running fine with Rails 5.0.2 and Ruby 2.4.0.

Should have looked into the issue a little further!
