### ISSUE TITLE
"no acceptor" rspec error

### ISSUE THREAD

**Issue by jackorp** [guard/guard-livereload#178]
When testing with rspec I get these "no acceptor" runtime error:
~~~
$ rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 21744
.....#<Thread:0x000055da96ae5030@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
#<Thread:0x000055da96a9f648@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
#<Thread:0x000055da96b94d78@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
#<Thread:0x000055da96be27a8@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
#<Thread:0x000055da96e0b6b0@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
..#<Thread:0x000055da96e8ae60@/builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	4: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	3: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:171:in `run'
	2: from /builddir/build/BUILD/guard-livereload-2.5.2/usr/share/gems/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:51:in `block in _start_reactor'
	1: from /usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_server'
/usr/share/gems/gems/eventmachine-1.2.5/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
............................

Finished in 0.20113 seconds (files took 0.30055 seconds to load)
35 examples, 0 failures

Randomized with seed 21744
~~~

Gem list output:
~~~
$ gem list

*** LOCAL GEMS ***

cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
diff-lcs (1.3)
em-spec (0.2.7)
em-websocket (0.5.1)
etc (default: 1.0.0)
eventmachine (1.2.5)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
guard-compat (1.2.1)
http_parser.rb (0.6.0)
io-console (0.4.6)
ipaddr (default: 1.2.0)
json (2.1.0)
multi_json (1.12.1)
openssl (2.1.0)
psych (3.0.2)
rake (12.3.0)
rdoc (6.0.1)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-support (3.7.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
webrick (default: 1.4.2)
zlib (default: 1.0.0)
~~~

Ruby version is 2.5.0
Tests are ran on mock, fedora-rawhide-x86_64.
Feedback appreciated.

**Comment by meganemura** [comment]
> no acceptor (port is in use or requires root privileges) (RuntimeError)

I think you are running another guard process.

**Comment by jackorp** [comment]
I don't think that is the problem. The tests are run in mock container environment, so no additional guard processes should be running.

**Comment by elijahmurray** [comment]
Any luck with this?
