### ISSUE TITLE
Error "Could not parse data entirely (0 != 609) (HTTP::Parser::Error)"

### ISSUE THREAD

**Issue by AlexWayfer** [guard/guard-livereload#179]
:frowning_face: 

```
#<Thread:0x000055ecc7024ef0@/home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
	5: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:50:in `_start_reactor'
	4: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	3: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	2: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:78:in `receive_data'
	1: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-livereload-2.5.2/lib/guard/livereload/websocket.rb:19:in `dispatch'
/home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-livereload-2.5.2/lib/guard/livereload/websocket.rb:19:in `<<': Could not parse data entirely (0 != 609) (HTTP::Parser::Error)
```

**Comment by AlexWayfer** [comment]
Why `2.5.2` version in RubyGems (Feb 4, 2016) has other source without 3d2d962716c2cbfccdba1d90e04f39e80e8101e9 from the same day?

And why there is `2.5.1` version in source code? https://github.com/guard/guard-livereload/blob/v2.5.2/lib/guard/livereload/version.rb#L3

Oh…

**Comment by AlexWayfer** [comment]
Version from `master` looks working for now.

**Comment by AlexWayfer** [comment]
It probably occurs only when the second connection appears…

**Comment by AlexWayfer** [comment]
> It probably occurs only when the second connection appears…

In the only one browser with multiple tabs everything is OK, but this exception occurs when you open the second browser (on another device) in parallel. :cry:
