### ISSUE TITLE
guard-livereload reports with undefined method epoll? error

### ISSUE THREAD

**Issue by Marin-Kitagawa** [guard/guard-livereload#188]
The following error is thrown when `bundle exec guard` is executed. 
```
18:27:17 - INFO - Run 'gem install win32console' to use color on Windows
#<Thread:0x000000000796e720 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:48:in `_start_reactor': undefined method `epoll?' for EventMachine:Module (NoMethodError)
Did you mean?  epoll
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11:in `block in initialize'
18:27:18 - INFO - Guard is now watching at 'Z:/RoR_WS/demo_blog'
For a better Pry experience on Windows, please use ansicon:
  https://github.com/adoxa/ansicon
If you use an alternative to ansicon and don't want to see this warning again,
you can add "Pry.config.windows_console_warning = false" to your pryrc.
[1] guard(main)>
```

How to resolve this?

**Comment by Adr1ann** [comment]
Someone solved that?

**Comment by sethhorsley** [comment]
I am getting this error on mac. Any updates on this?

**Comment by Artemiy17** [comment]
Same problem on mac.

**Comment by ordinz** [comment]
Same issue here

**Comment by alexvbush** [comment]
is this M1 specific bug? getting the same thing.

**Comment by avk** [comment]
I had this problem, and I traced it to EventMachine itself. 

It seems that the EventMachine object you get from `require 'em/pure_ruby'` doesn't have the same methods, like `epoll?`, as other builds. 

I had to first remove the gem:

```sh
$ gem uninstall eventmachine
```

and then reinstall from an unreleased build via this in my `Gemfile`:
```ruby
gem 'eventmachine', '= 1.3.0.dev.1', github: 'eventmachine/eventmachine', branch: 'master'
```

This idea and other approaches are described here: https://github.com/eventmachine/eventmachine/issues/960
