### ISSUE TITLE
"LoadError: cannot load such file -- 2.0/ruby_http_parser".

### ISSUE THREAD

**Issue by s4wny** [guard/guard-livereload#69]
guard-livereload doesn't work for me. When I run `guard` I get this error:

```
$ guard
DL is deprecated, please use Fiddle
14:57:28 - INFO - Guard uses TerminalTitle to send notifications.
14:57:29 - ERROR - Guard::LiveReload failed to achieve its <start>, exception was:
> [#B530D13781CB] LoadError: cannot load such file -- 2.0/ruby_http_parser
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.5.3-x86-mingw32/lib/ruby_http
_parser.rb:2:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in re
quire'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.5.3-x86-mingw32/lib/http_pars
er.rb:2:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in re
quire'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.5.3-x86-mingw32/lib/http/pars
er.rb:1:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.0/lib/em-websocket/handshake.
rb:1:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.0/lib/em-websocket.rb:15:in `
block in <top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.0/lib/em-websocket.rb:14:in `
each'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.0/lib/em-websocket.rb:14:in `
<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-livereload-1.1.3/lib/guard/livereload/re
actor.rb:1:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-livereload-1.1.3/lib/guard/livereload.rb
:26:in `start'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:99:in `block i
n run_supervised_task'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:97:in `catch'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:97:in `run_sup
ervised_task'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:54:in `block (
2 levels) in run'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:175:in `block
(3 levels) in scoped_guards'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:174:in `each'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:174:in `block
(2 levels) in scoped_guards'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:173:in `catch'

> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:173:in `block
in scoped_guards'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:172:in `each'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:172:in `scoped
_guards'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:53:in `block i
n run'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/lumberjack-1.0.3/lib/lumberjack.rb:27:in `unit
_of_work'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/runner.rb:52:in `run'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard.rb:189:in `block in star
t'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard.rb:365:in `block in with
in_preserved_state'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard.rb:362:in `synchronize'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard.rb:362:in `within_preser
ved_state'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard.rb:187:in `start'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/lib/guard/cli.rb:110:in `start'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `inv
oke_command'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
> [#B530D13781CB] c:/Ruby200/lib/ruby/gems/2.0.0/gems/guard-1.7.0/bin/guard:6:in `<top (required)>'
> [#B530D13781CB] c:/Ruby200/bin/guard:23:in `load'
> [#B530D13781CB] c:/Ruby200/bin/guard:23:in `<main>'
14:57:29 - INFO - Guard::LiveReload has just been fired
[1] guard(main)>  Guard is now watching at 'l:/www/'
```

Any clue why it doesn't work?

**EDIT#1:**
The problem is in guard/livereload/reactor.rb, at line 1, `require 'em-websocket'`.
 If I remove that line the error vanish.

**Comment by e2** [comment]
I'm closing this because it's probably outdated (dependencies have changed and gems have been updated since, Ruby 1.9.3 is EOL anyway).
